# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a2593a460e180e9baef7636f7eb6d57edcf14e594def49aaf3ac44b9d99c305e4e7ed273dad91d2792ac52997be2207c3a1ad8a9c1ebcd13de638ecb1e0ef98

test:
  secret_key_base: d7e4010f43db1017bf656d1ea8068919ec84594e44199ccf21a00dc40fed219dfff70263a23795c3cfee1fd5a6c12eff684d33bc5cf4d3023e1030a4d542a001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
